import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Bell, CalendarDays, Mail, MapPin, Search, Send, Users } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ArticleCard, CommunityTile, Composer, Empty, EventRow, OpportunityTile, PageHeading, PostCard, SectionHeading, articleImage, useCampusData } from "@/components/CampusContent";
import { content } from "@/lib/content";
import { useAuth, useIsAdmin, useProfile } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";
import { dateLong } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import campusStudents from "@/assets/campus-students.jpg";

export function HomePage() {
  const { articles, posts, events, communities, categories } = useCampusData();
  const featured = articles.data?.filter(a => a.featured) ?? [];
  const aside = <div className="space-y-5"><div className="border-b border-border pb-4"><SectionHeading title="Próximos eventos" to="/eventos" />{events.data?.filter(e => new Date(e.starts_at) >= new Date()).slice(0, 3).map(e => <EventRow key={e.id} event={e} />)}</div><div><SectionHeading title="Comunidades" to="/comunidades" />{communities.data?.slice(0, 3).map(c => <div key={c.id} className="mb-2"><CommunityTile community={c} /></div>)}</div></div>;
  return <AppShell aside={aside}><div className="space-y-8"><div><h1 className="text-2xl font-extrabold md:text-3xl">Bem-vindo ao InfoCampus <span className="text-primary">.</span></h1><p className="mt-1 text-sm text-muted-foreground">O que acontece no seu campus, em um só lugar.</p></div><Composer /><section><SectionHeading title="Destaques" to="/noticias" /><div className="scroll-x">{featured.length ? featured.map(a => <Link to="/artigo/$slug" params={{ slug: a.slug }} key={a.id} className="group relative h-56 w-[min(82vw,370px)] shrink-0 overflow-hidden rounded-md bg-muted"><img src={articleImage(a)} alt="" width={1280} height={720} className="absolute inset-0 h-full w-full object-cover transition-transform group-hover:scale-105" /><div className="absolute inset-0 bg-foreground/50" /><div className="absolute inset-x-0 bottom-0 p-5 text-primary-foreground"><span className="text-[10px] font-bold uppercase">{a.categories?.name}</span><h3 className="mt-1 line-clamp-2 text-lg font-extrabold leading-tight">{a.title}</h3></div></Link>) : <div className="relative h-56 w-full overflow-hidden rounded-md"><img src={campusStudents} alt="Estudantes do campus" width={1280} height={720} className="h-full w-full object-cover" /></div>}</div></section><section><SectionHeading title="Notícias recentes" to="/noticias" /><div className="grid gap-4 sm:grid-cols-2">{articles.data?.slice(0, 4).map(a => <ArticleCard key={a.id} article={a} />)}</div>{articles.data?.length === 0 && <Empty text="Nenhuma notícia publicada ainda." />}</section><section><SectionHeading title="Categorias em destaque" to="/noticias" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{categories.data?.map(c => <Link key={c.id} to="/categoria/$slug" params={{ slug: c.slug }} className="rounded-md border border-border bg-card p-4 text-center text-sm font-bold text-primary-deep hover:bg-accent">{c.name}</Link>)}</div></section><section><SectionHeading title="Da comunidade" /><div className="space-y-4">{posts.data?.slice(0, 8).map(p => <PostCard key={p.id} post={p} />)}{posts.data?.length === 0 && <Empty text="Seja a primeira pessoa a publicar." />}</div></section></div></AppShell>;
}
export function ListingPage({ kind }: { kind: "noticias" | "eventos" | "oportunidades" | "comunidades" | "artigos" }) {
  const { articles, events, opportunities, communities } = useCampusData();
  const config = { noticias: ["Notícias", "Acompanhe o que acontece no IFMA."], eventos: ["Eventos", "Encontros, oficinas e atividades do campus."], oportunidades: ["Oportunidades", "Vagas, bolsas e projetos para dar o próximo passo."], comunidades: ["Comunidades", "Encontre pessoas com os mesmos interesses."], artigos: ["Artigos", "Ideias e histórias da nossa comunidade."] }[kind];
  return <AppShell><PageHeading title={config[0]} subtitle={config[1]} />{(kind === "noticias" || kind === "artigos") && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{articles.data?.map(a => <ArticleCard key={a.id} article={a} />)}{articles.data?.length === 0 && <Empty />}</div>}{kind === "eventos" && <div className="grid gap-4 md:grid-cols-2">{events.data?.map(e => <div key={e.id} className="rounded-md border border-border bg-card px-5 py-3"><EventRow event={e} /><p className="pb-2 text-xs text-muted-foreground">{dateLong(e.starts_at)}</p></div>)}{events.data?.length === 0 && <Empty />}</div>}{kind === "oportunidades" && <div className="grid gap-4 md:grid-cols-2">{opportunities.data?.map(o => <OpportunityTile item={o} key={o.id} />)}{opportunities.data?.length === 0 && <Empty />}</div>}{kind === "comunidades" && <div className="grid gap-3 md:grid-cols-2">{communities.data?.map(c => <CommunityTile community={c} key={c.id} />)}{communities.data?.length === 0 && <Empty />}</div>}</AppShell>;
}
export function ExplorePage() {
  const { articles, posts, communities } = useCampusData(); const [term, setTerm] = useState(""); const q = term.trim().toLowerCase();
  return <AppShell><PageHeading title="Explorar" subtitle="Descubra notícias, conversas e comunidades." /><div className="relative mb-8"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={term} onChange={e => setTerm(e.target.value)} placeholder="O que você procura?" aria-label="Pesquisar" /></div><section className="mb-8"><SectionHeading title="Notícias e artigos" /><div className="grid gap-4 sm:grid-cols-2">{articles.data?.filter(a => `${a.title} ${a.subtitle} ${a.tags.join(" ")}`.toLowerCase().includes(q)).map(a => <ArticleCard article={a} key={a.id} />)}</div></section><section className="mb-8"><SectionHeading title="Comunidades" /><div className="grid gap-3 sm:grid-cols-2">{communities.data?.filter(c => `${c.name} ${c.description}`.toLowerCase().includes(q)).map(c => <CommunityTile key={c.id} community={c} />)}</div></section><section><SectionHeading title="Publicações" /><div className="space-y-4">{posts.data?.filter(p => p.content.toLowerCase().includes(q)).map(p => <PostCard key={p.id} post={p} />)}</div></section></AppShell>;
}
export function CategoryPage({ slug }: { slug: string }) { const { articles, categories } = useCampusData(); const category = categories.data?.find(c => c.slug === slug); const filtered = articles.data?.filter(a => a.categories?.slug === slug); return <AppShell><PageHeading title={category?.name ?? "Categoria"} subtitle={category?.description ?? undefined} /><div className="grid gap-4 sm:grid-cols-2">{filtered?.map(a => <ArticleCard key={a.id} article={a} />)}{filtered?.length === 0 && <Empty />}</div></AppShell>; }
export function ArticlePage({ slug }: { slug: string }) {
  const { data: articles } = useQuery({ queryKey: ["articles"], queryFn: content.articles }); const article = articles?.find(a => a.slug === slug); const { user } = useAuth(); const [comment, setComment] = useState(""); const queryClient = useQueryClient();
  const { data: comments } = useQuery({ queryKey: ["article-comments", article?.id], enabled: !!article, queryFn: async () => { const { data } = await supabase.from("comments").select("id,content,profiles(full_name)").eq("article_id", article?.id ?? "").order("created_at"); return data ?? []; } });
  async function submit(e: FormEvent) { e.preventDefault(); if (!user) return toast.error("Entre para comentar."); if (!article || !comment.trim()) return; const { error } = await supabase.from("comments").insert({ article_id: article.id, author_id: user.id, content: comment.trim() }); if (error) toast.error(error.message); else { setComment(""); queryClient.invalidateQueries({ queryKey: ["article-comments", article.id] }); toast.success("Comentário enviado!"); } }
  return <AppShell>{!article ? <Empty text="Artigo não encontrado." /> : <article className="mx-auto max-w-3xl"><Link to="/categoria/$slug" params={{ slug: article.categories?.slug ?? "institucional" }} className="text-xs font-extrabold uppercase text-primary-deep">{article.categories?.name}</Link><h1 className="mt-3 text-3xl font-extrabold leading-tight md:text-4xl">{article.title}</h1><p className="mt-3 text-base text-muted-foreground">{article.subtitle}</p><p className="mt-5 text-xs text-muted-foreground">Por {article.profiles?.full_name ?? "InfoCampus"} · {dateLong(article.created_at)}</p><img src={articleImage(article)} alt="" width={1280} height={720} className="mt-7 aspect-video w-full rounded-md object-cover" /><div className="mt-8 whitespace-pre-line text-base leading-8">{article.content}</div><div className="mt-10 border-t border-border pt-6"><SectionHeading title="Comentários" />{comments?.map(c => <div key={c.id} className="mb-2 rounded-md bg-muted p-3 text-sm"><b>{c.profiles?.full_name}</b><p className="mt-1">{c.content}</p></div>)}<form onSubmit={submit} className="mt-4 flex gap-2"><Input value={comment} onChange={e => setComment(e.target.value)} aria-label="Comentário" placeholder="Deixe seu comentário..." /><Button type="submit" aria-label="Enviar comentário"><Send /></Button></form></div></article>}</AppShell>;
}
export function ProfilePage({ username }: { username: string }) {
  const { user } = useAuth(); const { data: self } = useProfile(); const { posts, articles } = useCampusData();
  const { data: profile } = useQuery({ queryKey: ["public-profile", username], queryFn: async () => { const { data, error } = await supabase.from("profiles").select("*").eq("username", username).maybeSingle(); if (error) throw error; return data; } });
  return <AppShell>{!profile ? <Empty text="Perfil não encontrado." /> : <><div className="border-b border-border pb-7"><div className="flex flex-wrap items-center gap-5"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-primary-soft text-2xl font-bold text-primary-deep">{profile.avatar_url ? <img src={profile.avatar_url} alt="" className="h-full w-full object-cover" /> : profile.full_name[0]}</div><div className="flex-1"><h1 className="text-2xl font-extrabold">{profile.full_name}</h1><p className="text-sm text-muted-foreground">@{profile.username}</p><p className="mt-2 text-sm">{profile.bio}</p><p className="mt-2 text-xs text-muted-foreground">Na comunidade desde {dateLong(profile.created_at)}</p></div>{self?.id === profile.id && <Button asChild variant="outline"><Link to="/configuracoes">Editar perfil</Link></Button>}</div></div><section className="mt-8"><SectionHeading title="Publicações" /><div className="space-y-4">{posts.data?.filter(p => p.author_id === profile.id).map(p => <PostCard post={p} key={p.id} />)}{posts.data?.filter(p => p.author_id === profile.id).length === 0 && <Empty />}</div></section><section className="mt-8"><SectionHeading title="Artigos" /><div className="grid gap-4 sm:grid-cols-2">{articles.data?.filter(a => a.author_id === profile.id).map(a => <ArticleCard article={a} key={a.id} />)}</div></section></>}</AppShell>;
}
export function SettingsPage() {
  const { user } = useAuth(); const { data: profile } = useProfile(); const queryClient = useQueryClient(); const [busy, setBusy] = useState(false);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!user) return; const form = new FormData(e.currentTarget); setBusy(true); const { error } = await supabase.from("profiles").update({ full_name: String(form.get("full_name") ?? ""), bio: String(form.get("bio") ?? ""), avatar_url: String(form.get("avatar_url") ?? "") || null }).eq("id", user.id); setBusy(false); if (error) toast.error(error.message); else { toast.success("Perfil atualizado!"); queryClient.invalidateQueries({ queryKey: ["profile"] }); } }
  return <AppShell><PageHeading title="Configurações" subtitle="Atualize suas informações de perfil." />{!user ? <LoginPrompt /> : profile && <form key={profile.id} onSubmit={save} className="max-w-xl space-y-4"><div><Label htmlFor="full_name">Nome completo</Label><Input id="full_name" name="full_name" defaultValue={profile.full_name} required /></div><div><Label htmlFor="bio">Sobre você</Label><Textarea id="bio" name="bio" defaultValue={profile.bio ?? ""} /></div><div><Label htmlFor="avatar_url">Link da foto de perfil</Label><Input id="avatar_url" name="avatar_url" type="url" defaultValue={profile.avatar_url ?? ""} /></div><Button type="submit" disabled={busy}>{busy ? "Salvando..." : "Salvar alterações"}</Button></form>}</AppShell>;
}
export function LoginPrompt() { return <div className="py-12 text-center"><p className="mb-4 text-sm text-muted-foreground">Entre na sua conta para acessar esta página.</p><Button asChild><Link to="/entrar">Entrar</Link></Button></div>; }
export function MessagesPage() {
  const { user } = useAuth(); const [recipient, setRecipient] = useState(""); const [text, setText] = useState(""); const queryClient = useQueryClient();
  const { data: messages } = useQuery({ queryKey: ["messages", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("messages").select("id,content,created_at,sender_id,recipient_id").or(`sender_id.eq.${user?.id},recipient_id.eq.${user?.id}`).order("created_at", { ascending: false }); if (error) throw error; return data; } });
  async function send(e: FormEvent) { e.preventDefault(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("id").eq("username", recipient.replace(/^@/, "").trim()).maybeSingle(); if (!profile) return toast.error("Usuário não encontrado."); if (profile.id === user.id) return toast.error("Escolha outra pessoa."); const { error } = await supabase.from("messages").insert({ sender_id: user.id, recipient_id: profile.id, content: text.trim() }); if (error) toast.error(error.message); else { setText(""); toast.success("Mensagem enviada!"); queryClient.invalidateQueries({ queryKey: ["messages"] }); } }
  return <AppShell><PageHeading title="Mensagens" subtitle="Converse com outras pessoas do campus." />{!user ? <LoginPrompt /> : <div className="max-w-2xl"><form onSubmit={send} className="space-y-3 border-b border-border pb-6"><Label htmlFor="recipient">Nome de usuário</Label><Input id="recipient" value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="@ana.souza" required /><Label htmlFor="message">Mensagem</Label><Textarea id="message" value={text} onChange={e => setText(e.target.value)} placeholder="Escreva uma mensagem..." required /><Button type="submit"><Send /> Enviar mensagem</Button></form><div className="mt-6 space-y-3">{messages?.map(m => <div key={m.id} className="rounded-md border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{m.sender_id === user.id ? "Enviada" : "Recebida"} · {dateLong(m.created_at)}</p><p className="mt-1 text-sm">{m.content}</p></div>)}{messages?.length === 0 && <Empty text="Você ainda não tem mensagens." />}</div></div>}</AppShell>;
}
export function NotificationsPage() { const { user } = useAuth(); const queryClient = useQueryClient(); const { data } = useQuery({ queryKey: ["notifications", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("notifications").select("*").eq("user_id", user?.id ?? "").order("created_at", { ascending: false }); if (error) throw error; return data; } }); return <AppShell><PageHeading title="Notificações" subtitle="Novidades para você." />{!user ? <LoginPrompt /> : <div className="space-y-3">{data?.map(n => <div key={n.id} className="flex items-center gap-3 rounded-md border border-border bg-card p-4"><Bell className="h-5 w-5 text-primary-deep" /><p className="flex-1 text-sm">{n.message}</p>{!n.read && <Button size="sm" variant="ghost" onClick={async () => { await supabase.from("notifications").update({ read: true }).eq("id", n.id); queryClient.invalidateQueries({ queryKey: ["notifications"] }); queryClient.invalidateQueries({ queryKey: ["unread-notifications"] }); }}>Marcar como lida</Button>}</div>)}{data?.length === 0 && <Empty text="Nenhuma notificação por enquanto." />}</div>}</AppShell>; }
export function WriteArticlePage() { const { user } = useAuth(); const { data: categories } = useQuery({ queryKey: ["categories"], queryFn: content.categories }); const navigate = useNavigate(); const [busy, setBusy] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!user) return; const form = new FormData(e.currentTarget); const title = String(form.get("title") ?? "").trim(); const slug = `${title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${Date.now().toString(36)}`; setBusy(true); const { error } = await supabase.from("articles").insert({ title, slug, subtitle: String(form.get("subtitle") ?? ""), content: String(form.get("content") ?? ""), cover_url: String(form.get("cover_url") ?? "") || null, category_id: String(form.get("category_id") || "") || null, author_id: user.id }); setBusy(false); if (error) toast.error(error.message); else { toast.success("Artigo publicado!"); navigate({ to: "/artigo/$slug", params: { slug } }); } } return <AppShell><PageHeading title="Escrever artigo" subtitle="Compartilhe conhecimento com a comunidade." />{!user ? <LoginPrompt /> : <form onSubmit={submit} className="max-w-2xl space-y-4"><div><Label htmlFor="title">Título</Label><Input id="title" name="title" required /></div><div><Label htmlFor="subtitle">Subtítulo</Label><Input id="subtitle" name="subtitle" /></div><div><Label htmlFor="cover_url">Imagem de capa (link)</Label><Input id="cover_url" name="cover_url" type="url" /></div><div><Label htmlFor="category_id">Categoria</Label><select id="category_id" name="category_id" className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione uma categoria</option>{categories?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label htmlFor="content">Conteúdo</Label><Textarea id="content" name="content" className="min-h-64" required /></div><Button type="submit" disabled={busy}>{busy ? "Publicando..." : "Publicar artigo"}</Button></form>}</AppShell>; }
export function AdminPage() { const { user } = useAuth(); const { data: isAdmin } = useIsAdmin(); const { articles, posts, communities } = useCampusData(); return <AppShell><PageHeading title="Painel admin" subtitle="Visão geral da comunidade." />{!user ? <LoginPrompt /> : isAdmin ? <div className="grid gap-4 sm:grid-cols-3">{[["Artigos", articles.data?.length], ["Publicações", posts.data?.length], ["Comunidades", communities.data?.length]].map(([label, value]) => <div key={String(label)} className="rounded-md border border-border bg-card p-6"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-extrabold text-primary-deep">{value ?? "—"}</p></div>)}</div> : <Empty text="Você não tem permissão para acessar este painel." />}</AppShell>; }
export function LegalPage({ kind }: { kind: "termos" | "privacidade" }) { return <AppShell><div className="mx-auto max-w-2xl"><PageHeading title={kind === "termos" ? "Termos de uso" : "Política de privacidade"} /><p className="text-sm leading-7 text-muted-foreground">O InfoCampus é um espaço de troca entre estudantes da comunidade acadêmica do IFMA. Respeite as outras pessoas, publique apenas conteúdo que você tem direito de compartilhar e não divulgue dados pessoais de terceiros.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">As informações do seu perfil e as publicações são visíveis para outras pessoas. Mensagens privadas são acessíveis apenas às pessoas envolvidas. Para solicitar alteração ou exclusão de informações, entre em contato com a administração da comunidade.</p></div></AppShell>; }
export function ResetPasswordPage() { const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/entrar` }); setBusy(false); if (error) toast.error(error.message); else toast.success("Confira sua caixa de entrada para recuperar sua senha."); } return <AppShell><div className="mx-auto max-w-md"><PageHeading title="Recuperar senha" subtitle="Enviaremos um link para o seu e-mail institucional." /><form onSubmit={submit} className="space-y-4"><Label htmlFor="reset-email">E-mail institucional</Label><Input id="reset-email" type="email" value={email} onChange={e => setEmail(e.target.value)} required /><Button type="submit" disabled={busy}>{busy ? "Enviando..." : "Enviar link"}</Button></form></div></AppShell>; }
